# Generated by Django 4.0.4 on 2022-08-31 05:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRUDApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, upload_to='media/uploads')),
                ('Bio', models.CharField(max_length=200)),
                ('SocialMediaLinks', models.CharField(max_length=100)),
                ('CourseName', models.CharField(max_length=100)),
                ('CourseDuration', models.DurationField()),
                ('YearOfPassing', models.CharField(max_length=50)),
                ('Percentage', models.CharField(max_length=10)),
                ('CompanyNameORInternshipName', models.CharField(max_length=200)),
                ('DurationOfJobORInternship', models.CharField(max_length=100)),
                ('YourJobDescription', models.CharField(max_length=500)),
                ('SallaryORStipendInLPA', models.CharField(max_length=50)),
                ('ProjectName', models.CharField(max_length=200)),
                ('DurationOfProject', models.CharField(max_length=100)),
                ('ProjectDescription', models.CharField(max_length=1000)),
                ('YourRoleInProject', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
