# Generated by Django 4.0.4 on 2022-08-31 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUDApp', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='CourseDuration',
            field=models.CharField(max_length=100),
        ),
    ]
